name: Schedule Task

on:
  push:
    branches:
      - main # Replace with your branch name
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 4,5' # Executes at 00:00 UTC on Thursdays and Fridays

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Generate Weekly News
        run: node tech.js
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
