name: Schedule Task

on:
  push:
    branches:
      - main # Replace with your branch name
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 4,5' # Executes at 00:00 UTC on Thursdays and Fridays
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Generate Weekly News
        run: npm run build
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
